apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: gowtham
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxpod
  template:
    metadata:
      labels:
        app: nginxpod
    spec:
      containers:
        - name: nginx
          image: busybox:latest
          ports:
            - containerPort: 80

