---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: gowtham
spec:
  selector:
    app: nginxpod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
